# Generated by Django 4.0.4 on 2023-02-17 06:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonedaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProveedorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('no_ruc', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(default='aceptado', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=400, null=True)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('stock', models.IntegerField(default=0)),
                ('moneda', models.CharField(default='cordobas', max_length=50)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime(2023, 2, 17, 6, 5, 46, 759755))),
                ('fecha_modifiacion', models.DateTimeField()),
                ('estado', models.CharField(default='aceptado', max_length=50)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ingresos.categoriamodel')),
            ],
        ),
        migrations.CreateModel(
            name='IngresoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(auto_now=True)),
                ('no_factura', models.CharField(max_length=100)),
                ('moneda', models.CharField(default='cordobas', max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estado', models.CharField(default='aceptado', max_length=50)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ingresos.proveedormodel')),
            ],
        ),
        migrations.CreateModel(
            name='IngresoDetallesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('precio_compra_unidad', models.DecimalField(decimal_places=2, max_digits=6)),
                ('precio_venta_unidad', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingresos.ingresomodel')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ingresos.proveedormodel')),
            ],
        ),
    ]
