# Generated by Django 4.0.4 on 2023-02-17 06:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosmodel',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 17, 6, 10, 16, 206942)),
        ),
        migrations.AlterField(
            model_name='productosmodel',
            name='fecha_modifiacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 17, 6, 10, 16, 206955)),
        ),
    ]
