# Generated by Django 4.0.4 on 2023-02-17 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0002_alter_productosmodel_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosmodel',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 17, 6, 12, 20, 808447)),
        ),
        migrations.AlterField(
            model_name='productosmodel',
            name='fecha_modifiacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
