# Generated by Django 4.0.4 on 2023-02-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_productosmodel_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosmodel',
            name='codigo',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
